# Generated by Django 4.1.2 on 2022-11-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TESTUser_Login',
            new_name='arcdatacsv',
        ),
    ]
