# Generated by Django 4.1.2 on 2022-11-02 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_testuser_login_arcdatacsv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arcdatacsv',
            old_name='arc_capacity',
            new_name='arccap',
        ),
        migrations.RenameField(
            model_name='arcdatacsv',
            old_name='access_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='arcdatacsv',
            old_name='net_id',
            new_name='netid',
        ),
    ]
