# Generated by Django 4.1.2 on 2022-11-02 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_arc_capacity_arcdatacsv_arccap_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ARC_Section',
        ),
        migrations.DeleteModel(
            name='Insight',
        ),
    ]
