name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./docker_tutorial/backend/requirements.txt
    - name: Format with black
      run: |
        pip install black
        # format the files with black
        cd backend/
        black .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Sort imports
      run: |
        pip install isort
        # stop the build if there are Python syntax errors or undefined names
        cd backend/
        isort .
        isort --check --diff .
    - name: Run tests
      run: |
          cd backend/
          pytest
    - name: Generate Report
      run: |
        pip install coverage
        cd backend/
        pwd
        ls -al
        coverage run -m pytest
        
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
    - name: Code Coverage
      run:  |
          cd backend/
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          pwd
          ls -al
          ./codecov